### ISSUE TITLE
Task List for the Project (test)

### ISSUE THREAD

**Issue by Simon-Belanger** [JonathanCauchon/ULaval_PDK_Development#7]
List of things we need to do:
- [x] Create working environment and clone proper libraries. @JonathanCauchon 
- [ ] Choose Klayout working directory. @Simon-Belanger 
- [ ] Find a way to distribute the libraries for the tapeout users @Simon-Belanger 
- [ ] Write a functionnal analysis in order to plan future development.
- [ ] Write a wiki to present information to the PDK users.
- [ ] Find more information about updating the packages. Should we update them automatically (tapeouts?).
